### PR TITLE
i965 : Optimize atom state flag checks

### PR DESCRIPTION
**Pull request by amuthuk1**
This patch improves CPI Rate(Cycles per Instruction) and branch miss predict
for i965. The function check_state() was showing CPI retired rate.

Performance stats with android:
- CPI retired lowered by 28% (lower is better)
- Branch missprediction lowered by 13% (lower is better)
- 3DMark improved by 2%

### CODE REVIEW

**Comment by tpalli** [comment]
I'll make measurements with this tomorrow, if I find some I can try to show these improvements in mesa-dev mail thread. My recommendation is not to do this if upstream does not accept it, otherwise Android-IA project would need to live with this patch forever.

**Comment by amuthuk1** [comment]
patch1_results
Thanks Tapani for taking up the request. After when its found in your testing that the results have improved, would you please consider include it in our internal builds, since this patch improves every KPI/metric by 2% ?

Parallely, we are investigating the reason on why the results have improved.  We are seeing improvements in all the CPU metrics. For Ex Icache Misses had reduced, Branch Predictions had reduced.

**Comment by amuthuk1** [comment]
Thanks for taking up the request. Would you consider including this patch once after your testing has shown good results since this has shown improvement in every KPI by 2%?


Meanwhile, we are investigating on the reason of performance improvement using this patch.

**Comment by tpalli** [comment]
I've commented on the mesa thread, I'll also try to run some benchmarks on desktop Linux.

**Pull request closed without merging**
